const fs=require('fs'),path=require('path');const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/Seba/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const root=__dirname,b=await chromium.launch({headless:true,channel:'msedge'}),p=await b.newPage(),data={};const pages=['index.html','product.html','stories/index.html',...Array.from({length:5},(_,i)=>`stories/us${i+1}.html`),'prototype.html','delivery.html','qa.html'];for(const file of pages){await p.setContent(fs.readFileSync(path.join(root,'source/baseline',file),'utf8'));const result=await p.evaluate(file=>{const q=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];document.body.dataset.page=file==='stories/index.html'?'stories':file.replace('.html','');const word=q('.wordmark');word.innerHTML='<span class="identity-mark" aria-hidden="true">SA</span><span class="identity-name">Sebastian Amodio<span class="identity-context">Case Study - Nybble Group</span></span>';word.setAttribute('aria-label','Sebastian Amodio - Case Study - Nybble Group');
if(file==='index.html'){const hero=document.createElement('div');hero.className='overview-layout';const copy=document.createElement('div');copy.className='overview-copy';copy.append(q('.page-heading'),q('.overview-top'),q('.presentation-footer'));const art=document.createElement('div');art.className='ocean-art';art.setAttribute('aria-hidden','true');hero.append(copy,art);q('main').append(hero)}
if(file==='product.html'){all('.product-tile').forEach((x,i)=>{x.classList.add('tile-'+i);const icon=document.createElement('span');icon.className='tile-symbol';icon.setAttribute('aria-hidden','true');icon.textContent=['◎','↗','✧','＋','−'][i];x.prepend(icon)})}
if(file==='stories/index.html'){const workspace=document.createElement('div');workspace.className='story-workspace';q('.story-tools').before(workspace);workspace.append(q('.story-tools'),q('#story-detail'));all('.story-tabs a').forEach(x=>{const parts=x.textContent.split(' · ');x.innerHTML='<span class="story-code">'+parts[0]+'</span><span>'+parts[1]+'</span>'})}
if(/stories\/us\d/.test(file)){all('.criterion').forEach(x=>{const heading=x.querySelector('.criterion-heading');heading?.classList.add('criterion-meta')});all('p.bullet').forEach(x=>x.classList.add('clean-bullet'))}
if(file==='prototype.html'){const enter=document.createElement('button');enter.type='button';enter.id='expand-prototype';enter.textContent='Full screen';enter.setAttribute('aria-haspopup','dialog');q('.prototype-toolbar').append(enter);const modal=document.createElement('dialog');modal.id='prototype-fullscreen';modal.className='prototype-fullscreen';modal.setAttribute('aria-label','Interactive demo — full screen');modal.innerHTML='<div class="fullscreen-toolbar"><span>Interactive demo</span><div class="fullscreen-controls"><button type="button" id="exit-prototype-fullscreen">Exit full screen</button></div></div>';document.body.append(modal);const script=document.createElement('script');script.src='fullscreen.js';script.defer=true;document.head.append(script);}
if(file==='delivery.html'){all('.module-selectors a').forEach((x,i)=>{const span=document.createElement('span');span.className='module-number';span.setAttribute('aria-hidden','true');span.textContent='0'+(i+1);x.prepend(span)});all('p.bullet').forEach(x=>x.classList.add('clean-bullet'))}
return {html:'<!doctype html>'+document.documentElement.outerHTML,story:/stories\/us\d/.test(file)?all('main > section').map(x=>x.outerHTML).join(''):null};},file);fs.writeFileSync(path.join(root,file),result.html);if(result.story)data[file.match(/us\d/)[0]]=result.story}fs.writeFileSync(path.join(root,'story-data.js'),'window.storyContent='+JSON.stringify(data)+';');await b.close();require('./upgrade.cjs');require('./theme.cjs');})();


