const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');const {chromium}=require('C:/Users/Seba/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const root=path.resolve(__dirname,'..'),b=await chromium.launch({headless:true,channel:'msedge'}),p=await b.newPage({viewport:{width:1250,height:794}}),base='http://127.0.0.1:4184/',results=[];const check=async(name,fn)=>{await fn();results.push({name,result:'PASS'});console.log('PASS '+name)};const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(base+'stories/index.html');await check('Five stories and section navigation',async()=>{for(let n=1;n<=5;n++){await p.locator('[data-story="us'+n+'"]').click();assert.equal(await p.locator('#story-detail .criterion').count(),[4,4,5,8,5][n-1]);await p.locator('.story-jumps a').filter({hasText:'Decisions'}).click();await p.waitForTimeout(60);const target=await p.locator('#us'+n+'-decisions').boundingBox(),tools=await p.locator('.story-tools').boundingBox();assert.ok(target.y>=(await p.locator('.site-header').boundingBox()).height-2,'heading obscured');assert.ok(tools.y>=0);assert.equal(await p.locator('#us'+n+'-references img').count(),[2,1,1,2,1][n-1])}});
await check('Story retained after prototype and Back history',async()=>{await p.locator('.presentation-footer .next-page').click();await p.locator('.presentation-footer .secondary').click();assert.equal(await p.locator('[data-story][aria-current]').getAttribute('data-story'),'us5');await p.locator('[data-story="us2"]').click();await p.goBack();assert.equal(await p.locator('[data-story][aria-current]').getAttribute('data-story'),'us5')});
await p.goto(base+'delivery.html');await check('Delivery tabs remain available',async()=>{for(const id of ['quality','change-control','sequencing']){await p.locator('[data-module="'+id+'"]').click();assert.equal(await p.locator('.delivery-module:visible').count(),1);assert.ok((await p.locator('.module-selectors').boundingBox()).y>=0)}});
await check('Mobile selector and layouts',async()=>{for(const width of [390,320]){await p.setViewportSize({width,height:844});for(const file of ['index.html','product.html','stories/index.html','prototype.html','delivery.html','qa.html']){await p.goto(base+file);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),file+' '+width)}await p.goto(base+'stories/index.html');await p.locator('#story-select').selectOption('us4');assert.equal(await p.locator('#story-detail .criterion').count(),8);await p.locator('.story-jumps a').filter({hasText:'Criteria',exact:true}).click();await p.waitForTimeout(80);assert.ok((await p.locator('#us4-criteria').boundingBox()).y>=(await p.locator('.story-tools').boundingBox()).y+(await p.locator('.story-tools').boundingBox()).height-2)}});
await p.setViewportSize({width:1250,height:794});await p.goto(base+'prototype.html');await check('Prototype past-month guard and simulated search',async()=>{await p.locator('#reset-prototype').click();await p.locator('#trigger-date').click();assert.equal(await p.locator('.month:disabled').count(),9);await p.locator('.month[aria-label^="May 2027,"]').click();await p.locator('.month[aria-label^="September 2027,"]').click();await p.locator('[data-action="search"]').click();assert.match(await p.locator('#submission').innerText(),/Simulated search outcome/)});
await check('Backup unchanged',async()=>{for(const f of JSON.parse(fs.readFileSync(path.join(root,'evidence/v3-backup.json'))))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.resolve(root,'../deliverable-v3',f.path))).digest('hex'),f.sha256,f.path)});
for(const [file,name]of [['stories/index.html','stories'],['delivery.html','delivery'],['prototype.html','prototype']]){await p.goto(base+file);await p.screenshot({path:path.join(root,'evidence/v4-'+name+'.png')})}await p.setViewportSize({width:390,height:844});await p.goto(base+'stories/index.html#us4');await p.screenshot({path:path.join(root,'evidence/v4-mobile.png')});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'evidence/review.json'),JSON.stringify({results,errors,time:new Date().toISOString()},null,2));await b.close()})();
